import Foundation

enum AnalyticsEvent: String {
    case appOpened = "app_opened"
    case sessionRestored = "session_restored"
    case onboardingStarted = "onboarding_started"
    case onboardingCompleted = "onboarding_completed"
    case languageSelected = "language_selected"

    case authViewOpened = "auth_view_opened"
    case authEmailSignupTapped = "auth_email_signup_tapped"
    case authEmailLoginTapped = "auth_email_login_tapped"
    case authAppleTapped = "auth_apple_tapped"
    case authGoogleTapped = "auth_google_tapped"
    case authSuccess = "auth_success"
    case authFailed = "auth_failed"
    case signupCompleted = "signup_completed"

    case todayLoaded = "today_loaded"
    case dailyWordOpened = "daily_word_opened"
    case pronunciationPlayed = "pronunciation_played"
    case wordMarkedLearned = "word_marked_learned"
    case wordFavorited = "word_favorited"
    case dailyWordPlayPronunciation = "daily_word_play_pronunciation"
    case dailyWordMarkedLearned = "daily_word_marked_learned"
    case dailyWordFavorited = "daily_word_favorited"
    case dailyWordSavedForReview = "daily_word_saved_for_review"
    case dailyWordShareTapped = "daily_word_share_tapped"
    case wordDetailOpened = "word_detail_opened"

    case reviewOpened = "review_opened"
    case reviewStarted = "review_started"
    case reviewCompleted = "review_completed"
    case reviewAnswerSubmitted = "review_answer_submitted"
    case reviewAnswerCorrect = "review_answer_correct"
    case reviewAnswerIncorrect = "review_answer_incorrect"
    case reviewQueueEmpty = "review_queue_empty"

    case archiveOpened = "archive_opened"
    case archiveSearchUsed = "archive_searched"
    case archiveFilterChanged = "archive_filter_changed"
    case archiveSortChanged = "archive_sort_changed"
    case archiveWordOpened = "archive_word_opened"
    case relatedWordOpened = "related_word_opened"

    case progressOpened = "progress_opened"
    case profileOpened = "profile_opened"
    case profileUpdated = "profile_updated"
    case settingsOpened = "settings_opened"
    case settingsUpdated = "settings_updated"
    case streakExtended = "streak_extended"

    case notificationsEducationViewed = "notifications_education_viewed"
    case notificationsPermissionRequested = "notifications_permission_requested"
    case notificationsPermissionResult = "notifications_permission_result"
    case notificationPermissionGranted = "notification_permission_granted"
    case reminderTimeSet = "reminder_time_set"
    case pushOpened = "push_opened"
    case pushTokenRegistered = "push_token_registered"

    case paywallOpened = "paywall_opened"
    case paywallViewed = "paywall_viewed"
    case subscriptionStarted = "subscription_started"
    case paywallPlanSelected = "paywall_plan_selected"
    case purchaseStarted = "purchase_started"
    case purchaseSuccess = "purchase_success"
    case purchaseFailed = "purchase_failed"
    case restorePurchasesTapped = "restore_purchases_tapped"
    case accountDeleted = "account_deleted"
}
